### ISSUE TITLE
k8s bazel rules

### ISSUE THREAD

**Issue by peternavr** [lucperkins/colossus#2]
Do you have any plans on adding https://github.com/bazelbuild/rules_k8s?

**Comment by lucperkins** [comment]
I was thinking about it. Please feel free to submit a PR if you have any specific ideas.

**Comment by peternavr** [comment]
I have a working example, I'm having one issue trying to get a k8s deployment object to use the newly created image.

**Comment by lucperkins** [comment]
I might be having a similar issue. I was working on using `docker_push` rules rather than using `bazel run` to push the images to the Docker registry. The push seems to work (using `localhost:5000` as the `registry` parameter), but then I get `ErrImageNeverPull` in Minikube.

Actually, hmmm, wait, sounds like your issue is different 😄 Well, curious to see what you come up with anyway!

**Comment by lucperkins** [comment]
I won't have the bandwidth to pursue this for a while, as I'm largely stuck on getting Minikube to work with a local Docker registry. I'm going to close this issue for now.

Pull requests welcome, though!

**Comment by tmc** [comment]
It seems natural that this project would use https://github.com/bazelbuild/rules_k8s -- have you had a chance to explore that further?

**Comment by lucperkins** [comment]
As before, pull requests are welcome
